### ISSUE TITLE
Fedora 臺灣的專用 Logo

### ISSUE THREAD

**Issue by zerng07** [linux-taiwan/fedora.linux.org.tw#16]
我有去 Fedora Project 去申請了可以合法使用的地方社群 Logo，SVG 檔如下：
https://fedorahosted.org/design-team/attachment/ticket/388/388%20Fedora%20Taiwan%20logo.svg

有了這個 SVG 源檔，就可以拿來自己轉隨意要的大小的點陣圖了。

話說，如果有 FAS 帳號，可以看這篇當初申請的 Ticket：
https://fedorahosted.org/design-team/ticket/388

**Comment by kidwm** [comment]
網頁可以用 SVG 啊

**Comment by wildskyf** [comment]
是要直接把這個替換掉嗎？
![2015-07-07 21-35-22](https://cloud.githubusercontent.com/assets/6042803/8547248/24f97b6a-24f0-11e5-8f0c-d69c7e8bb6b4.png)

**Comment by zerng07** [comment]
因為自己做的沒有符合 Logo Guideline。
如果想要那麼長串字，可以直接改 SVG！

**Comment by zerng07** [comment]
如果要用 Fedora TAIWAN COMMUNITY 就改那個 SVG 就好了。

https://fedoraproject.org/wiki/Logo/UsageGuidelines

然後根據 Guideline，那個 fedora logo 代表的是 Fedora 這個 Linux 或 Fedora Project，要指到才能用。所以不能拿來當花邊的裝飾圖用。XD

**Comment by wildskyf** [comment]
嗚嗚，所以我剛剛給 h2 加的也不能用囉Orz

**Comment by zerng07** [comment]
答對了！XD

**Comment by wildskyf** [comment]
已更新了～

**Comment by kidwm** [comment]
所以有要換首頁上的 LOGO 嗎？

**Comment by wildskyf** [comment]
其實我比較喜歡現在這樣:S

**Comment by kidwm** [comment]
我是覺得換了也沒差
