### ISSUE TITLE
Fedora 臺灣的募款方式

### ISSUE THREAD

**Issue by zerng07** [linux-taiwan/fedora.linux.org.tw#17]
這方面我有和軟體自由協會談，線下 ATM 的捐款方法 OK 了，文案我也寫好了。募來的錢會用在相關 fedora 社群上，包括網域什麼的。

線上捐款的方式比較棘手，原本是打算透過 KKTIX 募款，但是開帳號是要付費的，而且 KKTIX 會扣取 6% 手續費跟 30 元匯款費，所以還在想怎樣線上募款才不會讓捐款者失血太多...

等確立之後我會把募款方式寫一寫丟上來這樣。XD
在線上捐款方法確定前，只會提供線下 ATM 捐款這個方法。

**Comment by zerng07** [comment]
軟體自由協會已經發布了，所以我馬上來弄。XD
http://www.slat.org/node/111
http://www.slat.org/node/112

**Comment by wildskyf** [comment]
扯開話題一下，"我們是誰"裡面的文案可以直接使用嗎XD 所有文件各式裡面，plain text 真的是最困難的一個各式啊哈哈…

**Comment by zerng07** [comment]
可以啊~

**Comment by zerng07** [comment]
fixed by b52b15e85e1324c95abc123c436f85793f5aa920
