### ISSUE TITLE
Fedora 一詞的使用

### ISSUE THREAD

**Issue by zerng07** [linux-taiwan/fedora.linux.org.tw#18]
根據官方對 Fedora 的說明，Fedora 代表的就是稱為 Fedora 的 Linux 作業系統 (註冊商標)，應該直接使用 Fedora 來指這個作業系統而不是 Fedora Linux，其中 F 應該大寫。

總之就是跟法律、商標有的沒的繁瑣官僚體系有關，有空來全面改一下。

**Comment by zerng07** [comment]
然後根據商標使用規定 [1]，社群網站的 Footer 要寫 This site is not affiliated with or endorsed by the Fedora Project 才可以使用「Fedora」這個商標。

[1] https://fedoraproject.org/wiki/Legal:Trademark_guidelines#Noncommercial_and_community_web_sites

**Comment by wildskyf** [comment]
「本網站不隸屬於 Fedora 專案，且不獲其授權。」
這樣嗎?

不知道怎麼翻比較好…

**Comment by zerng07** [comment]
就維持原文即可，給官方看的。

**Comment by wildskyf** [comment]
了解

**Comment by wi1d5ky** [comment]
不知道到底怎麼放比較好…
![Uploading 2015-07-12 00-53-36 的螢幕擷圖.png…]()

**Comment by wildskyf** [comment]
不知道到底怎麼放比較好…
![2015-07-12 00-53-36](https://cloud.githubusercontent.com/assets/6042803/8634578/89145c9e-2830-11e5-86a1-67234fc9a46d.png)

**Comment by zerng07** [comment]
OK, 醬應該就可以了。

**Comment by kidwm** [comment]
@zerng07 所以這個 issue 可以關了嗎？

**Comment by zerng07** [comment]
還不行，因為左上角的 Title 還沒改。

**Comment by zerng07** [comment]
基本上，就是要用「Fedora」取代掉「Fedora Linux」這樣。
