### ISSUE TITLE
broken layout

### ISSUE THREAD

**Issue by wildskyf** [linux-taiwan/fedora.linux.org.tw#19]
RWD 時 footer 的文字會有問題…

**Comment by kidwm** [comment]
那就修啊，順便把 header 照我上次說的方式改

**Comment by wildskyf** [comment]
等等有空來修，不過我還是想不到要怎麼變成整頁右移而不用 js@@
能用 checkbox:checked ~ ul.nav 是因為 ul.nav 是在 checkbox 下一個，可是 html, body 不是呀@@

**Comment by kidwm** [comment]
@wi1d5ky 只移選單不就好了…沒說一定要整頁右移啊
