### ISSUE TITLE
add forum feed to main page

### ISSUE THREAD

**Issue by kidwm** [linux-taiwan/fedora.linux.org.tw#21]
https://fedora-tw.org/latest.json

**Comment by wildskyf** [comment]
這個不是已經加了嗎XD
http://fedora.linux.org.tw/community/

不過剛意外發現 typo 就是了…

**Comment by kidwm** [comment]
那我改一下目標好了。

**Comment by wildskyf** [comment]
話說這個要去哪裡講？

**Comment by kidwm** [comment]
下次 Release Party 直接問 @FreedomKnight 好了

**Comment by kidwm** [comment]
@FreedomKnight 拜託你了，務必要解決它 Orz
https://meta.discourse.org/t/how-to-enable-cross-origin-resource-sharing-with-docker/15413

**Comment by wi1d5ky** [comment]
我的 code 已準備好，就等這個問題解決就可以推上來了！

**Comment by kidwm** [comment]
@wi1d5ky 現在的狀況是？

**Comment by wildskyf** [comment]
已接上，但樣式需要再美化。

**Comment by wildskyf** [comment]
@kidwm 現在的樣式還有哪裡要改善的嗎？沒有的話這張票要不要 close 了？

**Comment by kidwm** [comment]
好啊
