### ISSUE TITLE
feodra 臺灣的 telegram 加入連結失效

### ISSUE THREAD

**Issue by zerng07** [linux-taiwan/fedora.linux.org.tw#23]
目前的加入連結為 https://telegram.me/fedora_tw

不過 community 頁面下的加入連結還是 https://telegram.me/joinchat/BGbpBwIdS8gSkbxan-Lvmw

**Comment by wildskyf** [comment]
ref: 5f5d59ca9f1fe30ba902efe223104380630bc027

**Comment by wildskyf** [comment]
@zerng07 確認後就 close 吧！
